spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/learboot?characterEncoding=utf8
    username: root
    password: 123
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #thymeleaf的配置
  thymeleaf:
    prefix: classpath:/templates/webapp/web/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    #开发时候为false.缓存
    cache: false


  #redis相关配置
  redis:
    host: 116.62.59.0
    port: 6379
    password: Jslx07131qaz2wsx
    timeout: 1000
    jedis:
      pool:
        max-wait: 1000
        max-idle: 10
        max-active: 8
        min-idle: 0


  mail:
    host: smtp.qq.com
    username: 782529153@qq.com
    password: omowmvqdxjqibecc
    port: 587
    protocol: smtp
    properties:
         mail:
           smth:
             auth: true
             starttls:
               enable: true
               required: true


